name: Cloudlog Helper Cross Build

permissions:
  contents: write
  actions: write

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      
#      - name: Execute test
#        shell: pwsh
#        run: |
#          dotnet test
#
#      - name: Setup Cygwin environment
#        uses: egor-tensin/setup-cygwin@v4

      - name: Build application
        shell: pwsh
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $tagName = "${{ github.ref_name }}"
          if ([string]::IsNullOrEmpty($tagName)) {
            $tagName = "dev"
          }else{
            $tagName = $tagName -replace '^[vV]', ''
          }
          ./ci.ps1 -Version "$tagName"

      - name: Release it
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src/CloudlogHelper/bin/*.zip